packages:
  - apps/*
  - libraries/*
  - packages/*
  - react/*
  - tools/*

allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  esbuild: true

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
