name: release
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  code:
    uses: cyberuni/.github/.github/workflows/pnpm-verify.yml@main
    with:
      node-version: '[18, 20]'

  release:
    uses: cyberuni/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit

  docgen:
    uses: cyberuni/.github/.github/workflows/pnpm-docs.yml@main
    needs: release
    with:
      publish-dir: ./apps/storybook/storybook-static